export { default as Header } from './header/Header'
export { default as HomeBanner } from './homeBanner/HomeBanner'
export { default as About } from './about/About'
export { default as WhyUS } from './whyus/WhyUS'
export { default as Conditions } from './conditions/Conditions'
export { default as Pricing } from './pricing/Pricing'